import { makeElement } from './elements';
import type { StudioElement } from './types';
export const templates: Record<
  string,
  { width: number; height: number; elements: StudioElement[] }
> = {
  social: {
    width: 1080,
    height: 1080,
    elements: [
      makeElement('rect', {
        name: 'Background',
        x: 70,
        y: 70,
        width: 940,
        height: 940,
        radius: 64,
        fill: '#EEE9FF',
        stroke: 'none',
      }),
      makeElement('ellipse', {
        name: 'Sun',
        x: 700,
        y: 120,
        width: 240,
        height: 240,
        fill: '#FFCA68',
        stroke: 'none',
      }),
      makeElement('text', {
        name: 'Headline',
        x: 150,
        y: 300,
        width: 700,
        height: 220,
        text: 'Build\nbeautiful.',
        fontSize: 108,
        fontWeight: 800,
        fill: '#201D27',
        stroke: 'none',
      }),
      makeElement('rect', {
        name: 'Color block',
        x: 150,
        y: 700,
        width: 360,
        height: 120,
        radius: 60,
        fill: '#7656EE',
        stroke: 'none',
        rotation: -6,
      }),
    ],
  },
  poster: {
    width: 720,
    height: 960,
    elements: [
      makeElement('rect', {
        name: 'Backdrop',
        x: 0,
        y: 0,
        width: 720,
        height: 960,
        fill: '#19171F',
        stroke: 'none',
      }),
      makeElement('ellipse', {
        name: 'Red sun',
        x: 350,
        y: 460,
        width: 410,
        height: 410,
        fill: '#FF655E',
        stroke: 'none',
      }),
      makeElement('text', {
        name: 'Number',
        x: 70,
        y: 90,
        width: 500,
        height: 180,
        text: 'NO. 04',
        fontSize: 104,
        fontWeight: 800,
        fill: '#FFFFFF',
        stroke: 'none',
      }),
      makeElement('text', {
        name: 'Caption',
        x: 78,
        y: 315,
        width: 350,
        height: 70,
        text: 'FORM / SPACE / COLOR',
        fontSize: 20,
        fontWeight: 600,
        letterSpacing: 3,
        fill: '#B6B1C1',
        stroke: 'none',
      }),
    ],
  },
  logo: {
    width: 800,
    height: 800,
    elements: [
      makeElement('rect', {
        name: 'Gold background',
        x: 70,
        y: 70,
        width: 660,
        height: 660,
        radius: 170,
        fill: '#FFCA68',
        stroke: 'none',
      }),
      makeElement('rect', {
        name: 'Mark plate',
        x: 230,
        y: 230,
        width: 340,
        height: 340,
        radius: 100,
        fill: '#201E24',
        stroke: 'none',
        rotation: 8,
      }),
      makeElement('text', {
        name: 'Letter mark',
        x: 325,
        y: 280,
        width: 190,
        height: 200,
        text: 'V',
        fontSize: 190,
        fontWeight: 800,
        fill: '#FFFFFF',
        stroke: 'none',
      }),
    ],
  },
};
