(function (root) {
  "use strict";
  const presets = [
    {
      id: "sphere",
      group: "Quadrics",
      keywords: "球 球面",
      name: "Sphere",
      type: "A familiar starting point",
      expression: "x^2 + y^2 + z^2 = 4",
      span: 3,
    },
    {
      id: "torus",
      group: "Sculpted",
      keywords: "环面 圆环",
      name: "Torus",
      type: "A ring with a little room inside",
      expression: "(x^2+y^2+z^2+1.5^2-0.55^2)^2 = 9(x^2+y^2)",
      span: 2.6,
    },
    {
      id: "saddle",
      group: "Quadrics",
      keywords: "鞍面 双曲抛物面",
      name: "Saddle",
      type: "Curving in opposite directions",
      expression: "z = (x^2 - y^2)/2",
      span: 2.5,
    },
    {
      id: "gyroid",
      group: "Periodic",
      keywords: "螺旋 二十四面体 周期",
      name: "Gyroid",
      type: "An endlessly connected labyrinth",
      expression: "sin(x)cos(y) + sin(y)cos(z) + sin(z)cos(x) = 0",
      span: Math.PI,
    },
    {
      id: "ellipsoid",
      group: "Quadrics",
      keywords: "椭球",
      name: "Ellipsoid",
      type: "Three axes, three different radii",
      expression: "x^2/4 + y^2/2 + z^2 = 1",
      span: 2.6,
    },
    {
      id: "hyperboloid",
      group: "Quadrics",
      keywords: "单叶 双曲面",
      name: "Hyperboloid",
      type: "One continuous, open surface",
      expression: "x^2 + y^2 - z^2 = 1",
      span: 2.5,
    },
    {
      id: "cone",
      group: "Quadrics",
      keywords: "圆锥 双锥",
      name: "Double cone",
      type: "Two halves meeting at a point",
      expression: "x^2 + y^2 = z^2",
      span: 2.5,
    },
    {
      id: "wave",
      group: "Waves",
      keywords: "波浪 波面",
      name: "Wave",
      type: "A landscape of peaks and valleys",
      expression: "z = sin(x)cos(y)",
      span: Math.PI,
    },
    {
      id: "heart",
      group: "Sculpted",
      keywords: "心形 爱心",
      name: "Heart",
      type: "A little algebra, a lot of heart",
      expression: "(x^2+2.25y^2+z^2-1)^3 - x^2*z^3 - 0.1125y^2*z^3 = 0",
      span: 1.6,
    },
    {
      id: "schwarz",
      group: "Periodic",
      keywords: "施瓦茨 周期 隧道",
      name: "Schwarz P",
      type: "A periodic world of tunnels",
      expression: "cos(x) + cos(y) + cos(z) = 0",
      span: Math.PI,
    },
    {
      id: "two-spheres",
      group: "Combinations",
      keywords: "双球 分离",
      name: "Two spheres",
      type: "Disconnected parts of one equation",
      expression: "((x-1.2)^2+y^2+z^2-0.7^2)((x+1.2)^2+y^2+z^2-0.7^2) = 0",
      span: 2.5,
    },
    {
      id: "superellipsoid",
      group: "Sculpted",
      keywords: "超椭球 圆角立方体",
      name: "Superellipsoid",
      type: "Somewhere between sphere and cube",
      expression: "x^4 + y^4 + z^4 = 1",
      span: 1.6,
    },
    {
      id: "plane",
      name: "Oblique plane",
      group: "Quadrics",
      keywords: "平面 斜面",
      type: "A tilted slice through space",
      expression: "x + y + z = 0",
      span: 2.5,
    },
    {
      id: "cylinder",
      name: "Circular cylinder",
      group: "Quadrics",
      keywords: "圆柱 柱面",
      type: "A circle extended along the z axis",
      expression: "x^2 + y^2 = 1",
      span: 2,
    },
    {
      id: "elliptic-cylinder",
      name: "Elliptic cylinder",
      group: "Quadrics",
      keywords: "椭圆柱 柱面",
      type: "A cylinder with an elongated cross-section",
      expression: "x^2/2.25 + y^2/0.64 = 1",
      span: 2.2,
    },
    {
      id: "paraboloid",
      name: "Elliptic paraboloid",
      group: "Quadrics",
      keywords: "椭圆抛物面 碗",
      type: "An upward-opening bowl",
      expression: "z = (x^2 + y^2)/2",
      domain: [
        [-2.5, 2.5],
        [-2.5, 2.5],
        [-0.5, 3],
      ],
    },
    {
      id: "two-sheet",
      name: "Two-sheet hyperboloid",
      group: "Quadrics",
      keywords: "双叶 双曲面",
      type: "Two separated, opposing bowls",
      expression: "z^2 - x^2 - y^2 = 1",
      span: 2.5,
    },
    {
      id: "parabolic-cylinder",
      name: "Parabolic cylinder",
      group: "Quadrics",
      keywords: "抛物柱面",
      type: "A parabola swept along a straight line",
      expression: "z = x^2/2",
      domain: [
        [-2.5, 2.5],
        [-2.5, 2.5],
        [-0.5, 3],
      ],
    },
    {
      id: "hyperbolic-cylinder",
      name: "Hyperbolic cylinder",
      group: "Quadrics",
      keywords: "双曲柱面",
      type: "Two curved walls running in parallel",
      expression: "x^2 - y^2 = 1",
      span: 2.5,
    },
    {
      id: "octahedron",
      name: "Octahedron",
      group: "Sculpted",
      keywords: "八面体 多面体",
      type: "Eight faces from absolute values",
      expression: "abs(x) + abs(y) + abs(z) = 2",
      span: 2.5,
    },
    {
      id: "rounded-octahedron",
      name: "Rounded octahedron",
      group: "Sculpted",
      keywords: "圆角 八面体",
      type: "A softer transition between the axes",
      expression: "abs(x)^1.5 + abs(y)^1.5 + abs(z)^1.5 = 2",
      span: 2.1,
    },
    {
      id: "monkey-saddle",
      name: "Monkey saddle",
      group: "Sculpted",
      keywords: "猴鞍面 三重鞍面",
      type: "Three valleys around a single saddle",
      expression: "z = (x^3 - 3x*y^2)/3",
      span: 2.2,
    },
    {
      id: "cubic-sheet",
      name: "Cubic sheet",
      group: "Sculpted",
      keywords: "三次曲面",
      type: "A cubic profile with a sideways slope",
      expression: "z = x^3/3 - y",
      span: 2.3,
    },
    {
      id: "wavy-torus",
      name: "Wavy torus",
      group: "Sculpted",
      keywords: "波浪 环面 圆环",
      type: "A ring lifted into three gentle waves",
      expression: "(sqrt(x^2+y^2)-1.35)^2 + (z-0.2sin(3atan2(y,x)))^2 = 0.35^2",
      span: 2.1,
    },
    {
      id: "ripple",
      name: "Radial ripple",
      group: "Waves",
      keywords: "涟漪 径向 波纹",
      type: "Concentric waves fading outwards",
      expression: "z = cos(3sqrt(x^2+y^2))/(1+0.3(x^2+y^2))",
      domain: [
        [-3, 3],
        [-3, 3],
        [-1.3, 1.3],
      ],
    },
    {
      id: "egg-carton",
      name: "Egg carton",
      group: "Waves",
      keywords: "蛋盒 波面",
      type: "A regular landscape of peaks and valleys",
      expression: "z = 0.65(cos(2x) + cos(2y))",
      domain: [
        [-3.14, 3.14],
        [-3.14, 3.14],
        [-1.6, 1.6],
      ],
    },
    {
      id: "interference",
      name: "Interference",
      group: "Waves",
      keywords: "干涉 波纹",
      type: "Three wave directions in one surface",
      expression: "z = 0.45(sin(2x) + sin(2y) + sin(2(x+y)))",
      domain: [
        [-3.14, 3.14],
        [-3.14, 3.14],
        [-1.6, 1.6],
      ],
    },
    {
      id: "gaussian",
      name: "Gaussian hill",
      group: "Waves",
      keywords: "高斯 山峰 钟形",
      type: "A smooth peak that fades to a plain",
      expression: "z = 2exp(-x^2-y^2)",
      domain: [
        [-2.5, 2.5],
        [-2.5, 2.5],
        [-0.3, 2.5],
      ],
    },
    {
      id: "gaussian-ring",
      name: "Gaussian ring",
      group: "Waves",
      keywords: "高斯 环形 山脊",
      type: "A circular ridge with a quiet center",
      expression: "z = 1.6exp(-4(sqrt(x^2+y^2)-1.3)^2)",
      domain: [
        [-2.5, 2.5],
        [-2.5, 2.5],
        [-0.3, 2],
      ],
    },
    {
      id: "diamond",
      name: "Diamond network",
      group: "Periodic",
      keywords: "钻石 金刚石 网络 周期",
      type: "A trigonometric network of branching passages",
      expression:
        "sin(x)sin(y)sin(z)+sin(x)cos(y)cos(z)+cos(x)sin(y)cos(z)+cos(x)cos(y)sin(z)=0",
      span: Math.PI,
    },
    {
      id: "cosine-network",
      name: "Cosine network",
      group: "Periodic",
      keywords: "余弦 网络 周期",
      type: "Rounded chambers joined by narrow necks",
      expression: "3(cos(x)+cos(y)+cos(z))+4cos(x)cos(y)cos(z)=0",
      span: Math.PI,
    },
    {
      id: "gyroid-shell",
      name: "Gyroid shell",
      group: "Periodic",
      keywords: "螺旋 壳层 周期",
      type: "Two offset boundaries around a periodic sheet",
      expression: "abs(sin(x)cos(y)+sin(y)cos(z)+sin(z)cos(x))=0.28",
      span: Math.PI,
    },
    {
      id: "union",
      name: "Sphere union",
      group: "Combinations",
      keywords: "并集 双球 布尔",
      type: "Two overlapping spheres joined into one",
      expression: "min((x-0.7)^2+y^2+z^2-1,(x+0.7)^2+y^2+z^2-1)=0",
      span: 2.2,
    },
    {
      id: "intersection",
      name: "Sphere intersection",
      group: "Combinations",
      keywords: "交集 透镜 布尔",
      type: "The lens shared by two overlapping spheres",
      expression: "max((x-0.7)^2+y^2+z^2-1,(x+0.7)^2+y^2+z^2-1)=0",
      span: 1.2,
    },
    {
      id: "difference",
      name: "Sphere difference",
      group: "Combinations",
      keywords: "差集 布尔 月牙",
      type: "A spherical bite out of a larger sphere",
      expression: "max(x^2+y^2+z^2-2.25,-((x-0.9)^2+y^2+z^2-1.3^2))=0",
      span: 2,
    },
    {
      id: "crossed-tubes",
      name: "Crossed tubes",
      group: "Combinations",
      keywords: "交叉 圆管 并集",
      type: "Three tubes meeting along the coordinate axes",
      expression: "min(x^2+y^2-0.45^2,min(y^2+z^2-0.45^2,x^2+z^2-0.45^2))=0",
      span: 1.6,
    },
  ];
  const benchmarkPresets =
    typeof module !== "undefined" && module.exports
      ? require("./benchmark-presets.js")
      : root.SurfaceBenchmarkPresets;
  presets.push(...benchmarkPresets);
  root.SurfacePresets = presets;
  if (typeof module !== "undefined" && module.exports) module.exports = presets;
})(typeof globalThis !== "undefined" ? globalThis : this);
